title: Corporate
headline: Jual Segala Macam Perkakas Rumah Tangga
url: https://hakim.orderio.id/dev-orderio
description: Mau cari perlengkapan rumah? Pesan via chat WA di sini!
keywords: dekorasi, perkakas, rumah, tangga
ogp: /assets/upload/config/ogp.jpeg
phone_number: 6281234567890
whatsapp_number: 6281234567890
whatsapp_chat: |-
  Halo kak...
  Saya mau order :

