pros1:
  icon: /assets/upload/config/icon-expedition.png
  title: Pengiriman cepat
pros2:
  icon: /assets/upload/config/icon-secure.png
  title: Transaksi aman dan nyaman
pros3:
  icon: /assets/upload/config/icon-24h.png
  title: Layanan cepat 24 jam
